source 'https://rubygems.org'

gem 'power_boots', path: '../'
gem 'sinatra'
gem 'activerecord'
#gem 'activesupport'
gem 'bcrypt'
gem 'sqlite3'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end
